Assignment-1/Bmarketo/Controllers/ContactsController.cs
using Bmarketo.Models.Forms;
using Microsoft.AspNetCore.Mvc;

namespace Bmarketo.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index(string returnUrl = null!)
        {
            var form = new ContactFormModel { ReturnUrl = returnUrl ?? Url.Content("~/") };
            return View(form);
        }    

        [HttpPost]
        public IActionResult Index(ContactFormModel form)
        {
            return View(form);
        }
    }
}

Assignment-1/Bmarketo/Controllers/LoginController.cs
using Bmarketo.Models.Forms;
using Bmarketo.Services;
using Microsoft.AspNetCore.Mvc;

namespace Bmarketo.Controllers
{
    public class LoginController : Controller
    {
        private readonly AuthenticationService _authentication;

        public LoginController(AuthenticationService authentication)
        {
            _authentication = authentication;
        }

        public IActionResult Index(string returnUrl = null!)
        {
            var form = new LoginFormModel { ReturnUrl = returnUrl ?? Url.Content("~/") };
            return View(form);
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginFormModel form)
        {
            if (ModelState.IsValid)
            {
                var result = await _authentication.LoginAsync(form);
                if (result is OkResult)
                {
                    return LocalRedirect(form.ReturnUrl);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Incorrect email or password");
                }
            }
            
            return View(form);
        }
    }
}

Assignment-1/Bmarketo/Views/Shared/Partials/_ContactShowcase.cshtml
<section class="contact-showcase container">
    <img src="~/images/contact.jpg"/>
    <div class="title-1">
    <h1>CONTACT</h1>
    </div>
    <div class="title-2">
    <h2>HOME. CONTACT</h2>
    </div>
</section>

Assignment-1/Bmarketo/Views/Shared/Partials/_Footer.cshtml
<section class="footer">
    <div class="container">&copy; 2023 bmarketo. All right reserved.</div>
</section>

Assignment-1/Bmarketo/Views/Shared/Partials/_Header.cshtml
<section class="header container">
    <div class="logo">
        <a asp-controller="Home" asp-action="Index"><img src="~/images/logo.svg" alt="" /></a>
    </div>
    <nav class="menu">
        @if (User.IsInRole("Admin"))
        {
            <a class="menu-link" asp-controller="Admin" asp-action="Index">ADMIN CENTER</a>
        }
        <a class="menu-link" asp-controller="Home" asp-action="Index">HOME</a>
        <a class="menu-link" asp-controller="Products" asp-action="Index">PRODUCTS</a>
        <a class="menu-link" asp-controller="Contacts" asp-action="Index">CONTACT</a>
    </nav>
    <nav class="menulinkicons">
        <a class="menu-link" asp-controller="" asp-action=""><i class="fa-regular fa-magnifying-glass"></i></a>

        @if (User.Identity!.IsAuthenticated)
        {
            <a class="menu-link" asp-controller="Account" asp-action="Index">Account</a>
        }
        else
        {
         <a class="menu-link" asp-controller="Login" asp-action="Index">Login</a>
        }
        

        <a class="menu-link" asp-controller="" asp-action="">
            <i class="fa-sharp fa-regular fa-rectangle-vertical"></i>
        </a>
        <span class="menu-badge">2</span>
</nav>
</section>

Assignment-1/Bmarketo/Views/Shared/Partials/_LoginHeader.cshtml
<section class="header container">
    <div class="logo">
        <a asp-controller="Home" asp-action="Index"><img src="~/images/logo.svg" alt="" /></a>
    </div>

    <nav class="menulinkicons">
        <a class="menu-link" asp-controller="Login" asp-action="Index">Login</a>

        <a class="menu-link" asp-controller="" asp-action="">
            <i class="fa-sharp fa-regular fa-rectangle-vertical"></i>
        </a>
        <span class="menu-badge">2</span>
    </nav>
</section>

Assignment-1/Bmarketo/Views/Shared/Partials/_Map.cshtml
<section class="map container">
    <iframe
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41032.943179546244!2d17.97275725980134!3d59.32474523395833!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x465f763119640bcb%3A0xa80d27d3679d7766!2sStockholm!5e0!3m2!1sen!2sse!4v1676985055819!5m2!1sen!2sse"
    width="1920"
    height="825"
    style= border: 0 
    allowfullscreen=""
    loading="lazy"
    referrerpolicy="no-referrer-when-downgrade"
    ></iframe>
</section>

Assignment-1/Bmarketo/Views/Shared/Partials/_ProductShowcase.cshtml
<section class="product-showcase container">
    <img src="~/images/product-header.png" alt="Product Header"/>
    <div class="title-1">
        <h1>SHOP</h1>
    </div>
    <div class="title-2">
        <h2>HOME. PRODUCT DETAILS</h2>
    </div>
</section>